apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ptycoin-web 
  labels:
    name: ptycoin-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ptycoin-web
    spec:
      containers:
      - name: ptycoin-web
        image: {{IMAGE}}
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 10m

---
apiVersion: v1
kind: Service
metadata:
  name: ptycoin-web
  labels:
    name: ptycoin-web
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    name: ptycoin-web

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ptycoin-web
spec:
  backend:
    serviceName: ptycoin-web
    servicePort: 80
